- name: Copy script to AIX and CentOS 9 without Python or base64
  hosts: all
  gather_facts: no
  vars:
    script_local_path: ./my_script.sh
    script_remote_path: /tmp/my_script.sh

  tasks:
    - name: Read script content from control node
      delegate_to: localhost
      run_once: true
      slurp:
        src: "{{ script_local_path }}"
      register: slurped_script

    - name: Decode script content into plain text lines
      delegate_to: localhost
      run_once: true
      set_fact:
        script_lines: "{{ slurped_script.content | b64decode | split('\n') }}"

    - name: Generate heredoc payload
      delegate_to: localhost
      run_once: true
      set_fact:
        script_payload: |
          cat <<'EOF' > {{ script_remote_path }}
          {% for line in script_lines %}
          {{ line }}
          {% endfor %}
          EOF

    - name: Copy script to remote using heredoc via raw module
      raw: "{{ script_payload }}"

    - name: Make the script executable
      raw: "chmod +x {{ script_remote_path }}"
